### ISSUE TITLE
Proble

### ISSUE THREAD

**Issue by scaetano84** [PlushBeaver/xdp-syn-cookie#3]
Hi, when mount the program stop working SSH connections, any idea for this?

**Comment by PlushBeaver** [comment]
Note that this is a tutorial project not intended for production use. Please use "stand" script to setup a local testing environment.

~~After installing this program, only traffic from addresses that have passed the challenge will be accepted. That is, you must do a connection attempt (it will be reset), after that connections from the same address should succeed.~~

EDIT. Sorry, this project is so old that I forgot that it is incomplete. See https://github.com/PlushBeaver/xdp-syn-cookie/issues/1.

**Comment by scaetano84** [comment]
Ok, thank you, i going to test it. Can give me a email to contact you? thank you.
